// Generated from assets/ui/manifest.json by
// scripts/generate_ui_manifest_kf.py --format kofscript.
// Do not edit this file directly; regenerate it from the manifest.

String kookieUiPublishedUiGatogansoMarkId() { return "ui.gatoganso-mark" }
String kookieUiPublishedUiGatogansoMarkSource() { return "assets/ui/gatoganso-mark.svg" }
Int kookieUiPublishedUiGatogansoMarkKind() {
    return kookieUiScriptAssetSvg()
}
String kookieUiPublishedUiGatogansoMarkAlt() { return "GatoGanso mark" }
String kookieUiPublishedUiGatogansoMarkChecksum() { return "b8a5fa320e49bf41d06969ae8d918a70a5525a9c7271fbe073c7878798b0f17e" }

String kookieUiPublishedUiPlayerHeartsId() { return "ui.player-hearts" }
String kookieUiPublishedUiPlayerHeartsSource() { return "content/prototype/runtime/ui/hearts_0001.png" }
Int kookieUiPublishedUiPlayerHeartsKind() {
    return kookieUiScriptAssetPng()
}
String kookieUiPublishedUiPlayerHeartsAlt() { return "Player health" }
String kookieUiPublishedUiPlayerHeartsChecksum() { return "c468c974f5c044012c0d84ef57c6e3941f8472ab841fc030ea98d865013576d3" }
