#!/usr/bin/env python3
"""Generate the Kof UI asset bindings from the published UI manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from ui_manifest import load_ui_manifest
import re
import sys


KIND_FUNCTIONS = {
    "png": "kookieUiAssetPng",
    "svg": "kookieUiAssetSvg",
    "svgz": "kookieUiAssetSvgz",
}


def fail(message: str) -> None:
    raise SystemExit(f"generate_ui_manifest_kf: {message}")


def kof_string(value: object, field: str) -> str:
    if not isinstance(value, str) or not value:
        fail(f"{field} must be a non-empty string")
    if any(ord(character) < 32 for character in value):
        fail(f"{field} contains a control character")
    if '"' in value or "\\" in value:
        fail(f"{field} contains an unsupported Kof string delimiter")
    return json.dumps(value, ensure_ascii=False)




def symbol_suffix(asset_id: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", asset_id)
    if not parts:
        fail(f"asset id has no Kof symbol component: {asset_id}")
    suffix = "".join(part[0].upper() + part[1:] for part in parts)
    if not suffix[0].isalpha():
        fail(f"asset id cannot produce a Kof symbol: {asset_id}")
    return suffix


def load_assets(manifest_path: Path) -> list[dict[str, str]]:
    try:
        _, manifest_assets = load_ui_manifest(manifest_path)
    except ValueError as error:
        fail(str(error))

    result: list[dict[str, str]] = []
    seen_symbols: set[str] = set()
    for asset in manifest_assets:
        asset_id = asset["id"]
        kind = asset["kind"]
        symbol = "kookieUiPublished" + symbol_suffix(asset_id)
        if symbol in seen_symbols:
            fail(f"asset ids collide at generated symbol: {symbol}")
        seen_symbols.add(symbol)
        result.append(
            {
                "id": kof_string(asset_id, f"asset {asset_id} id"),
                "runtime_path": kof_string(
                    asset["runtime_path"], f"asset {asset_id} runtime_path"
                ),
                "kind_function": KIND_FUNCTIONS[kind],
                "alt": kof_string(asset["alt"], f"asset {asset_id} alt"),
                "sha256": kof_string(asset["sha256"], f"asset {asset_id} sha256"),
                "symbol": symbol,
            }
        )
    return result


def render(assets: list[dict[str, str]]) -> str:
    lines = [
        "package ui",
        "",
        "// Generated from assets/ui/manifest.json by scripts/generate_ui_manifest_kf.py.",
        "// Do not edit this file directly; regenerate it from the manifest.",
        "",
    ]
    for asset in assets:
        lines.extend(
            [
                f"KookieUiAsset {asset['symbol']}() {{",
                "    var asset = KookieUiAsset(",
                f"        {asset['id']},",
                f"        {asset['runtime_path']},",
                f"        {asset['kind_function']}(),",
                f"        {asset['alt']},",
                f"        {asset['sha256']})",
                "    return asset",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render(load_assets(args.manifest))
    if args.check:
        try:
            actual = args.output.read_text(encoding="utf-8")
        except OSError as error:
            fail(f"cannot read generated output: {error}")
        if actual != expected:
            fail(f"generated output is stale: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
